FROM python:3.11-slim

WORKDIR /app


COPY agent ./agent

RUN pip install --no-cache-dir \
    fastapi \
    "uvicorn[standard]" \
    langchain-mcp-adapters \
    langgraph \
    mcp \
    langchain-groq \
    python-dotenv 

EXPOSE 8000

CMD ["uvicorn", "agent.main:app", "--host", "0.0.0.0", "--port", "8000"]
